name = "KwatMDPhD"
uuid = "3c6b59ae-7a55-4292-9018-b718494ae969"
version = "0.1.0"
authors = ["KwatMDPhD"]

[deps]
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"

[compat]
GenieFramework = "3.0.1"
